version: '3'

volumes:
    wordpress: {}
    database: {}

services:
    mariadb:
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        image: mariadb
        restart: always
        init: true
        env_file: ./.env
        volumes:
            - database:/var/lib/mysql
            - ./volumes:/var/www/html
        networks:
            - intra
        tty: true

    wordpress:
        build:
            context: ./wordpress
            dockerfile: Dockerfile
        image: wordpress
        restart: always
        init: true
        env_file: ./.env
        depends_on:
            - mariadb
        volumes:
            - ./volumes:/var/www/html
        networks:
            - intra
        tty: true

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx
        restart: always
        init: true
        env_file: ./.env
        depends_on:
            - mariadb
            - wordpress
        ports:
            - "443:443"
        volumes:
            - ./volumes:/var/www/html
        networks:
            - intra
        tty: true

networks:
    intra:
        driver: bridge