# Generated by Django 5.1.1 on 2024-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('1vs1', '1VS1'), ('tournament', 'Tournament'), ('final', 'Final')], max_length=50, verbose_name='게임 종류'),
        ),
    ]
