# Generated by Django 5.1.1 on 2024-09-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='oauthid',
            field=models.IntegerField(default=0, unique=True, verbose_name='OAuth2.0'),
        ),
    ]
