# Generated by Django 5.1.1 on 2024-09-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tfa_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
