# Generated by Django 5.1.1 on 2024-09-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='t_nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='토너먼트 닉네임'),
        ),
    ]
