# Generated by Django 5.1.1 on 2024-09-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_tfa_active_user_otp_base32'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_tfa_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_base32',
        ),
    ]
