# Generated by Django 5.1.1 on 2024-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_tfa_active_remove_user_otp_base32'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tfa_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
