# Generated by Django 5.1.1 on 2024-09-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_t_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='t_loser',
            field=models.CharField(max_length=20, null=True, verbose_name='토너먼트 패배자'),
        ),
    ]
