# Generated by Django 5.1.1 on 2024-10-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_t_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tfa_setting',
            field=models.BooleanField(default=False),
        ),
    ]
