# Generated by Django 5.1.1 on 2024-09-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_tfa_active_user_otp_base32'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
