# Generated by Django 5.1.1 on 2024-10-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_tfa_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
