# Generated by Django 5.1.1 on 2024-10-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_otp_base32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
